#!/bin/bash

script_base="$(realpath $(dirname $0))"
cd $script_base

. op-build-env

#HACK: copy the machine specific patches
#to the top level directory of the machine-xml
#project
apply-machine-xml-patches ${1%%_*}

op-build $@
