#!/bin/bash
__PWD=`pwd`

if [ -e ./customrc ]; then
    source ./customrc
fi

if [ ! -e buildroot/Makefile ]; then
	echo "Please make sure you've checked out the buildroot submodule"
	echo "  git submodule init && git submodule update"
	return -1
fi

export BR2_EXTERNAL=${__PWD}/openpower
export BR2_DL_DIR=${__PWD}/dl

export LANG=en_US.UTF-8

apply-machine-xml-patches () {
	machine=$1
	if [ -z "$machine" ]
	then
		return 0;
	fi
	if [ -d openpower/package/machine-xml/$machine ]
	then
		rm -f openpower/package/machine-xml/*.patch
		cp -fl openpower/package/machine-xml/$machine/*.patch openpower/package/machine-xml/
	fi
	return 0;
}

op-build () {
    make --directory=${__PWD}/buildroot O=${__PWD}/output $@
}
